spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/gestao_financeira_processor_consumer
    username: devuser
    password: dev1234

  kafka:
    bootstrap-servers: kafka:29092

  jpa:
    hibernate:
      ddl-auto: validate

  flyway:
    enabled: true

server:
  port: 8083

  error:
    include-stacktrace: never


