services:

  # --------------------
  # KAFKA
  # --------------------
  kafka:
    image: apache/kafka-native:4.1.1
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_LISTENERS: LOCAL://:9092,DOCKER://:29092,CONTROLLER://:9093
      KAFKA_ADVERTISED_LISTENERS: LOCAL://localhost:9092,DOCKER://kafka:29092
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: LOCAL:PLAINTEXT,DOCKER:PLAINTEXT,CONTROLLER:PLAINTEXT
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@localhost:9093
      KAFKA_INTER_BROKER_LISTENER_NAME: DOCKER
      KAFKA_CLUSTER_ID: NjE2ZDY0NjU2ZTY5NmUyZQ==
    networks:
      - gestao-net

  # --------------------
  # POSTGRES - USUARIOS
  # --------------------
  postgres-usuarios:
    image: postgres:17
    container_name: postgres-usuarios
    environment:
      POSTGRES_DB: ms-service-usuario
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - postgres_usuarios:/var/lib/postgresql/data
    networks:
      - gestao-net

  # --------------------
  # POSTGRES - TRANSACOES
  # --------------------
  postgres-transacoes:
    image: postgres:17
    container_name: postgres-transacoes
    environment:
      POSTGRES_DB: ms-service-transacao
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - postgres_transacoes:/var/lib/postgresql/data
    networks:
      - gestao-net

  # --------------------
  # POSTGRES - PROCESSOR
  # --------------------
  postgres-processor:
    image: postgres:17
    container_name: postgres-processor
    environment:
      POSTGRES_DB: ms-processor-consumer
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - postgres_processor:/var/lib/postgresql/data
    networks:
      - gestao-net

  # --------------------
  # MS USUARIOS
  # --------------------
  ms-service-usuario:
    build: ./ms-service-usuario
    container_name: ms-service-usuario
    ports:
      - "8081:8080"
    environment:
      SPRING_PROFILES_ACTIVE: docker
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
    depends_on:
      - postgres-usuarios
    networks:
      - gestao-net

  # --------------------
  # MS TRANSACOES
  # --------------------
  ms-service-transacao:
    build: ./ms-service-transacao
    container_name: ms-service-transacao
    ports:
      - "8082:8080"
    environment:
      SPRING_PROFILES_ACTIVE: docker
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
    depends_on:
      - postgres-transacoes
      - kafka
    networks:
      - gestao-net

  # --------------------
  # MS PROCESSOR-CONSUMER
  # --------------------
  ms-processor-consumer:
    build: ./ms-processor-consumer
    container_name: ms-processor-consumer
    ports:
      - "8083:8083"
    environment:
      SPRING_PROFILES_ACTIVE: docker
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
    depends_on:
      - postgres-processor
      - kafka
    networks:
      - gestao-net

networks:
  gestao-net:
    driver: bridge

volumes:
  postgres_usuarios:
  postgres_transacoes:
  postgres_processor:
