version: '3.8'

services:
  postgres:
    image: postgres:17
    environment:
      POSTGRES_USER: devuser
      POSTGRES_PASSWORD: dev1234
      POSTGRES_DB: gestao_financeira_processor_consumer
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  kafka:
    image: apache/kafka-native:4.1.1
    ports:
      - "9092:9092"
    environment:
      - KAFKA_NODE_ID=1
      - KAFKA_PROCESS_ROLES=broker,controller
      - KAFKA_LISTENERS=LOCAL://:9092,DOCKER://:29092,CONTROLLER://:9093
      - KAFKA_ADVERTISED_LISTENERS=LOCAL://localhost:9092,DOCKER://kafka:29092
      - KAFKA_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=LOCAL:PLAINTEXT,DOCKER:PLAINTEXT,CONTROLLER:PLAINTEXT
      - KAFKA_CONTROLLER_QUORUM_VOTERS=1@localhost:9093
      - KAFKA_INTER_BROKER_LISTENER_NAME=DOCKER
      - KAFKA_CLUSTER_ID=NjE2ZDY0NjU2ZTY5NmUyZQ==
  pgadmin:
    image: dpage/pgadmin4

volumes:
  postgres_data: