spring:
  datasource:
    url: jdbc:postgresql://postgres-processor:5432/ms-processor-consumer
    username: ${DB_USER}
    password: ${DB_PASSWORD}

  kafka:
    bootstrap-servers: kafka:29092

  jpa:
    hibernate:
      ddl-auto: validate

  flyway:
    enabled: true

server:
  port: 8083
