api:
  security:
    token:
      secret: ${JWT_SECRET:12345678}

spring:
  application:
    name: transacoes-service

  kafka:
    bootstrap-servers: ${KAFKA_HOST:localhost:9092}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      group-id: transacoes-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"

    profiles:
      active: local

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true

  flyway:
    enabled: true
    locations: classpath:db/migration

exchangerateapi:
  cambio:
    url: https://v6.exchangerate-api.com/v6/2b5d7f40c5468cfed3925775/latest